### ISSUE TITLE
SAM stack cannot be updated anymore after referencing "AWS::ServiceCatalog::CloudFormationProvisionedProduct"

### ISSUE THREAD

**Issue by gpomykala** [aws-samples/aws-service-catalog-preventive-control#1]
We recently made a change to our app SAM template to use "AWS::ServiceCatalog::CloudFormationProvisionedProduct" instead of provisioning AWS resources (S3/DynamoDB) directly. 
Unfortunately after a successful deployment the stack cannot be updated anymore. We are getting a following error:
Resource of type 'AWS::ServiceCatalog::CloudFormationProvisionedProduct' with identifier 'pp-XXXX' was not found.

I verified with AWS CLI and Service Catalog UI that the provisioned product does exist and the user used to provision the stack has necessary Service Catalog permissions.

**Comment by RemekHet** [comment]
Is the product identifier pp-XXXX hard coded in your CF template?

**Comment by gpomykala** [comment]
pp-XXXX is not a product identifier, it is a 'provisioned product' identifier. I do not have it hardcoded in the template, the ids that are in the template are:
* product identifier prod-XXXXX
* product artifact identifier pa-XXXX

**Comment by RemekHet** [comment]
It’s hard to say what’s going on without taking look at your account and configuration. I would suggest open AWS support case.

**Comment by gpomykala** [comment]
Thanks, it turned out our infra team deleted a product and created another one with same name but another ID ;)
