### ISSUE TITLE
Hard-coded Account ID

### ISSUE THREAD

**Issue by myahl-uncomn** [aws-samples/aws-service-catalog-preventive-control#3]
Is this intentional or should we use our own account ID?

https://github.com/aws-samples/aws-service-catalog-preventive-control/blob/7c53e2c8dd37cc5068e166b65a8333a0024c14da/control-tower-account-factory/src/common.py#L401

**Comment by RemekHet** [comment]
it should be account where solution was deployed. Patch uploaded
